/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Numerology;

/**
 *
 * @author harih
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    public String l1;
    public int len,itr,s1=0,c1=0,b1,d1=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        value = new javax.swing.JTextField();
        numer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 80, 30));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 80, 30));

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 70, 30));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 310, 30));

        value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueActionPerformed(evt);
            }
        });
        jPanel1.add(value, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 120, -1));

        numer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerActionPerformed(evt);
            }
        });
        jPanel1.add(numer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 120, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, 20));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 50, 30));

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 50, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\harih\\Downloads\\resize-16445957451216149036748189.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 834, 493));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        nameActionPerformed(evt);
        len = l1.length();
        for (itr=0;itr<=len-1;itr++) {
            switch (l1.charAt(itr)) {
                case 'a':
                case 'j':
                case 'i':
                case 'y':
                case 'q':
                case 'A':
                case 'J':
                case 'I':
                case 'Y':
                case 'Q':
                    s1 = s1 + 1;
                    break;
                case 'b':
                case 'r':
                case 'k':
                case 'B':
                case 'K':
                case 'R':
                    s1 = s1 + 2;
                    break;
                case 'c':
                case 'g':
                case 'l':
                case 's':
                case 'C':
                case 'G':
                case 'L':
                case 'S':
                    s1 = s1 + 3;
                    break;
                case 'd':
                case 'D':
                case 'm':
                case 'M':
                case 't':
                case 'T':
                    s1 = s1 + 4;
                    break;
                case 'e':
                case 'E':
                case 'h':
                case 'H':
                case 'n':
                case 'N':
                case 'x':
                case 'X':
                    s1 = s1 + 5;
                    break;
                case 'u':
                case 'U':
                case 'v':
                case 'V':
                case 'w':
                case 'W':
                    s1 = s1 + 6;
                    break;
                case 'O':
                case 'o':
                case 'z':
                case 'Z':
                    s1 = s1 + 7;
                    break;
                case 'f':
                case 'F':
                case 'p':
                case 'P':
                    s1 = s1 + 8;
                    break;
                default:
                    break;
            }
	}
        String num = String.valueOf(s1);
        value.setText(num);
        if(9<=s1)
	{
	    while(s1>0) {
		b1 = s1 % 10;
		c1 = c1 + b1;
                s1 = s1 /10;
            }
            if(9<=c1)
            {
                while(c1>0)
                {
                    b1 = c1 % 10;
                    d1 = d1 + b1;
                    c1 = c1 / 10;
                }
                numer.setText(String.valueOf(d1));
            } else {
                numer.setText(String.valueOf(c1));
            }
	} else {
            numer.setText(String.valueOf(s1));
        }
        len = 0;
        itr = 0;
        s1 = 0;
        c1 = 0;
        b1 = 0;
        d1 = 0;
    }//GEN-LAST:event_searchActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        l1 = name.getText();
        l1 = l1.replace(" ","");
        //value.setText(l1);
        
    }//GEN-LAST:event_nameActionPerformed

    private void valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueActionPerformed
        // TODO add your handling code here:
        //String num = String.valueOf(s1);
        //value.setText(l1);
    }//GEN-LAST:event_valueActionPerformed

    private void numerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        name.setText("");
        value.setText("");
        numer.setText("");
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField numer;
    private javax.swing.JButton reset;
    private javax.swing.JButton search;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
